services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: secreta
      MYSQL_DATABASE: VistaPlus
      MYSQL_USER: admin
      MYSQL_PASSWORD: secreta
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/data
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: secreta
    restart: always
    ports:
      - 8091:80
    depends_on:
      - db

  backend:
    image: acordia2310/vista-plus-backend:latest
    build:
      context: ./Backend/VistaPlus
      dockerfile: Dockerfile
    restart: always
    environment:
      PERFIL_ACTIVO: prod
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/VistaPlus?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secreta
      
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: acordia2310/frontend-vista-plus:latest
    build:
      context: ./Frontend/FrontedVistaPlus
      dockerfile: Dockerfile
    restart: always
    environment:
      # [CONFIGURACIÓN DE ENTORNOS]
      # >>> LOCAL:
      #API_URL: http://localhost:8080
      # >>> VPS (Descomenta esta y comenta la de arriba si cambias de máquina):
      API_URL: http://192.168.9.150:8080
    ports:
      # [CONFIGURACIÓN DE ENTORNOS]
      # >>> LOCAL:
      #- "4200:4000"
      # >>> VPS (Descomenta esta para entrar directo por la IP y comenta la de arriba):
      - "80:4000"
    depends_on:
      - backend
volumes:
  dbdata: