-- GÉNEROS
INSERT INTO genero (nombre) VALUES
('Acción'),('Aventura'),('Comedia'),('Drama'),('Fantasía'),
('Ciencia Ficción'),('Terror'),('Romance'),('Misterio'),('Thriller'),
('Historia'),('Biografía'),('Deportes'),('Musical'),('Documental'),
('Anime'),('Manga'),('Superhéroes'),('Western'),('Noir'),
('Slice of Life'),('Isekai'),('Shounen'),('Shoujo'),('Seinen'),
('Josei'),('Mecha'),('Harem'),('Psicológico'),('Sobrenatural'),
('Magia'),('Post-apocalíptico'),('Cyberpunk'),('Steampunk'),
('Gore'),('Infantil'),('Familiar'),('Político'),('Filosófico'),
('Suspenso'),('Catástrofe'),('Épico'),('Satírico'),('Parodia'),
('Absurdo'),('Existencial'),('Tragicomedia'),('Melodrama'),
('Road Movie'),('Coming of Age'),('Found Footage'),('Mockumentary'),
('Artes Marciales'),('Espionaje'),('Militar'),('Supervivencia'),
('Cazarrecompensas'),('Piratas'),('Samurái'),('Ninja'),
('Gladiadores'),('Apocalíptico'),
('Alta Fantasía'),('Fantasía Urbana'),('Dark Fantasy'),
('Mitología'),('Folklore'),('Fairy Tale'),('Espada y Brujería'),
('Distopía'),('Utopía'),('Biopunk'),('Solarpunk'),('Dieselpunk'),
('Retrofuturismo'),('Space Opera'),('Space Western'),
('Hard Science Fiction'),('Soft Science Fiction'),('Time Travel'),
('Realismo Mágico'),
('Terror Psicológico'),('Terror Sobrenatural'),('Body Horror'),
('Slasher'),('Survival Horror'),('Lovecraftiano'),('Vampiros'),
('Zombies'),('Hombres Lobo'),('Demonios'),('Exorcismo'),
('Romance Histórico'),('Romance Sobrenatural'),('BL / Boys Love'),
('GL / Girls Love'),('Harem Inverso'),('Poliamoroso'),
('Edad Diferente'),('Rivals to Lovers'),
('Vida Escolar'),('Vida Universitaria'),('Trabajo y Oficina'),
('Gastronomía'),('Deporte Escolar'),('Club de Actividades'),
('Maternidad / Paternidad'),('Vejez'),('Amistad'),
('Isekai Inverso'),('Villainess'),('Reencarnación'),('Regresión'),
('LitRPG'),('Dungeon'),('Cultivation'),('Xuanhuan'),('Wuxia'),
('Manhua'),('Manhwa'),('Light Novel'),('Visual Novel'),
('Otome'),('Ecchi'),('Kodomomuke'),
('True Crime'),('Naturaleza'),('Ciencia y Tecnología'),
('Historia Política'),('Sociedad'),('Economía'),('Religión'),
('Arte y Cultura'),('Viajes'),('Deportes Extremos'),
('Biografía Musical'),('Autobiografía'),
('Ópera'),('Ballet'),('Concierto'),('Videoclip'),('Jukebox'),
('LGBTQ+'),('Feminismo'),('Racismo y Diversidad'),
('Discapacidad'),('Salud Mental'),('Adicciones'),
('Guerra y Conflicto'),('Refugiados'),('Crimen Organizado'),
('Hackers'),('Inteligencia Artificial'),('Realidad Virtual'),
('Viaje Espacial'),('Colonización'),('Contacto Extraterrestre'),
('Mutantes'),('Clonación'),('Pandemia'),('Ecología');

-- USUARIOS (2 USER, 2 AUTOR, 1 ADMIN)
INSERT INTO usuario (id, username, nacionalidad, email, password, fecha_nac, rol) VALUES 
(1, 'admin', 'Española', 'admin@mail.com', '$2a$10$7Z8nVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.TVuHOnu', '1990-01-01', 'ADMIN');